### ISSUE TITLE
Self-service recover

### ISSUE THREAD

**Issue by BlinkyStitt** [llamanodes/payment-contracts#1]
https://github.com/llamanodes/payment-contracts/blob/ef1327e9760bdad20de650b570384493839d6af8/contracts/Sweeper.vy#L39

This should be `assert msg.sender == FACTORY.payment_address_to_account(address(self))`. That way people can save themselves instead of having to get us to recover and then transfer for them.

**Comment by iamdefinitelyahuman** [comment]
Better yet, it can be both - in case the user has lost the original private key.

**Comment by iamdefinitelyahuman** [comment]
Added in f2602df

**Comment by BlinkyStitt** [comment]
Both is even better
