### ISSUE TITLE
allow base token payments

### ISSUE THREAD

**Issue by BlinkyStitt** [llamanodes/payment-contracts#2]
As is, the contracts can only support ERC20 payments. Should we support payment in the base token (ETH)? I think we might need a `receive` function on `MinimalProxy.vy` and another function on `Sweeper.vy`

**Comment by iamdefinitelyahuman** [comment]
At least to start, I think we'll only accept stablecoins. Otherwise we're effectively speculating on the price of ETH, or forced to be selling it as quickly as we're receiving it.

If we do decide to add this in the future we can use WETH or upgrade the contract.

**Comment by BlinkyStitt** [comment]
Sounds good. We can always make a zap that wraps and deposits
