### ISSUE TITLE
Less transfer

### ISSUE THREAD

**Issue by BlinkyStitt** [llamanodes/payment-contracts#5]
https://github.com/llamanodes/payment-contracts/blob/bb639e7321538ae5f4dc07dddc743c6eb772afe4/contracts/Sweeper.vy#L23-L25

we can get rid of the transfer, right? Just have transferFrom destination be the receiver. No need to hop through self

**Comment by iamdefinitelyahuman** [comment]
Yeah, I just did the extra hop so that the tokens show as passing through the address on etherscan. If they go directly to the sweeper, less technically minded users might struggle to see their payment histories.

**Comment by BlinkyStitt** [comment]
Ah that's reasonable. We can leave it
