### ISSUE TITLE
CREATE2

### ISSUE THREAD

**Issue by BlinkyStitt** [llamanodes/payment-contracts#6]
https://github.com/llamanodes/payment-contracts/blob/bb639e7321538ae5f4dc07dddc743c6eb772afe4/contracts/Factory.vy#L82

this line should salt with the _account. That way users get the same proxy address on every chain (or at least a deterministic one)

without a salt, addresses will be deterministic by the order deployed. This could be very confusing for users since they will likely have different addresses on different chains. Worse, those addresses are likely owned by someone else on other chains.

**Comment by BlinkyStitt** [comment]
Also, if we use create2, we don't need the assert at the start since the create_copy_of will revert. 

We don't even need the storage mapping of address -> proxy since it can be calculated. You have to hash some stuff concatted together. I asked in telegram about how best to do that. Would be nice if vyper had a helper. We should have a view function that takes the account and outputs the deterministic address that create2 gives

we should still keep the mapping of proxy address -> account

**Comment by BlinkyStitt** [comment]
I don't see a helper in vyper, but the address from a create2 deploy is `keccak256 ( concat(0xff, deployer address, bytes32 salt, keccak256 (init_code))) [12:]

**Comment by iamdefinitelyahuman** [comment]
This definitely makes sense.  Need to speak to the vyper devs I guess, and might end up having to use some Solidity :grimacing:

**Comment by BlinkyStitt** [comment]
Sad news, we can't get the init code in vyper.

Instead of rewriting the factory in solidity, lets just keep the storage mappings. This storage is just a small deploy time cost. Owner -> forwarder mapping will likely be used off chain anyways (where they can keccack the salt stuff themselves too). And we need the forwarder -> owner mapping even if it were in solidity.

Since the address is deterministic and create_copy_of reverts on duplicate, we can drop the first assert line.

```
@external
def create_payment_address(_account: address = msg.sender):
    sweeper: address = create_copy_of(PROXY_IMPLEMENTATION, salt = convert(_account, bytes32))
    self.account_to_payment_address[_account] = sweeper
    self.payment_address_to_account[sweeper] = _account

    log NewPaymentAddress(_account, sweeper)
```
