### ISSUE TITLE
add "indexed" to the account event

### ISSUE THREAD

**Issue by BlinkyStitt** [llamanodes/payment-contracts#9]
https://github.com/llamanodes/payment-contracts/blob/1f21071e064294829a1edc9763abd2f23cf96ec0/contracts/Factory.vy#L9

If our event subscription service misses a transaction and a user reports an issue, we can use this indexed account event argument to more quickly scan a wide range of blocks. At least, I think that is how `indexed` works. This way we don't even have to ask them for the txid (though if they provide it, we can use that too)

**Comment by iamdefinitelyahuman** [comment]
Implemented in commit 0aa46b509412122fcb9c31517aa2fa780f501578
